contrib/dxx-rebirth.xcodeproj/project.pbxproj
similar/arch/sdl/jukebox.cpp
similar/main/gamecntl.cpp

first commit fixes this problem:
```
Compiling d2x-rebirth build/d2x-rebirth-opengl/ similar/arch/sdl/jukebox.cpp
similar/arch/sdl/jukebox.cpp:143:10: error: use of overloaded operator '[]' is ambiguous (with operand types 'RAIIdmem<char []>' and 'uint_fast32_t' (aka 'unsigned int'))
list_buf[length] = '\0';        // make sure the last string is terminated
~~~~~~~~^~~~~~~
typename tt::enable_if<tt::rank<T>::value != 0, element_type &>::type operator[](std::size_t i) const
^
typename tt::enable_if<tt::rank<T>::value != 0, element_type &>::type operator[](int i) const
^
list_buf[length] = '\0';        // make sure the last string is terminated
^
1 error generated.
```
couple more on the way

more OS X issues

---

common/main/multi.h

even when compiling without USE_UDP, almost everything in multi.h is needed.
With this change, dxx-rebirth can be compiled with use_udp=False
I needed that to work because net_udp.cpp now causes clang to crash for some reason.

compiling without USE_UDP

---

common/main/ai.h
similar/main/ai.cpp
similar/main/collide.cpp
similar/main/mission.cpp
similar/main/multibot.cpp
similar/main/paging.cpp
similar/main/titles.cpp

Here's some little corrections for D1 emulation in d2x-rebirth. There is still a bunch of redundancy (two do_boss_stuff functions, etc) that could be merged, but I did this with as light a touch as possible and no noticeably wrong behavior.

D1 emulation issues

---

similar/arch/sdl/digi_mixer.cpp

There is a an out-of-bounds access in digi_mixer_start_sound() when
soundnum is < 0. The bounds check I added here is already present in
digi_audio_start_sound().
This bug was triggered on the RPi d2x built when trying to show the
briefing screen because briefing_new_screen() tries to play
SOUND_BRIEFING_HUM, which digi_xlat_sound() translated to -1 in this
situation. The game finally crashed in mixdigi_convert_sound() because
GameSounds[-1] happened to contain some non-zero data (on my Linux desktop,
that memory seems to be always 0 by accident...). This was also the reason
why the pi version tried to allocate lots of memory before it crashed in
memcpy().

Prevent digi_mixer_start_sound() from trying to play nonexisting sounds.

---

common/main/object.h
similar/arch/ogl/gr.cpp
similar/arch/ogl/ogl.cpp
similar/main/state.cpp

These patches make the RPi port compile again. There has always been some warnings about unused and uninitialized variables, which are now treated as errors, so fix those.
There is also a patch included which does not change the alignment of the `object_rw` structure for RPI builds, so that those should become compatible to desktop build network games, as well as savagame-compatible, as discussed here: 
http://www.dxx-rebirth.com/frm/index.php/topic,1986.msg21232.html#msg21232

Unification: RPi updates

---

common/include/maths.h
common/include/pstypes.h
common/main/multi.h
common/maths/fixc.cpp
common/texmap/scanline.cpp
d2x-rebirth/main/bmread.cpp

This removes the vestiges of weird non-standard u_int*_t types.
You'll probably want to just delete that whole section in pstypes.h, since these types have been around since C99, but I haven't tested any platforms that might be affected.

change u_int*_t to C99 standard uint*_t

---

similar/3d/interp.cpp

c4a84320817b9e02f86f3ec2dd2678e3367cddcc removed lots of inclusions of byteutil.h in various source files. However, when building with WORDS_NEED_ALIGNMENT, interp.cpp makes use of the INTEL_SHORT and GET_INTEL_SHORT macros defined there, breaking the RPi builds which it intented to fix.
Fixes: c4a84320817b9e02f86f3ec2dd2678e3367cddcc  ("Remove WORDS_NEED_ALIGNMENT memcpy src cast to const uint8_t*")

Restore inclusion of byteutil.h in similiar/3d/interp.cpp

---

similar/main/inferno.cpp

Add include directive for <locale>, fixing four compiler errors on Apple Clang.
I thought I would get you to review this first just in case. Still very green with C++!

Add include directive for <locale>

---

similar/editor/med.cpp
similar/editor/medwall.cpp

Save unique_ptr's to UI_GADGET_BUTTON's in similar/editor/med.cpp and similar/editor/medwall.cpp, preventing them from being deleted prematurely due to the behaviour of unique_ptr's. Fixes compile errors and resolves a crash when attempting to access both dialogs' gadgets (input event processing is the first attempt).
Not attempting any tidy up (moving globals into structs/classes) beyond the new button pointers, will do in a later commit.

Save more unique_ptr's to UI_GADGET_BUTTON's

---

common/arch/sdl/window.cpp
common/include/fwd-window.h
common/include/window.h
common/ui/dialog.cpp
common/ui/menubar.cpp
d2x-rebirth/main/escort.cpp
d2x-rebirth/main/movie.cpp
similar/editor/info.cpp
similar/main/automap.cpp
similar/main/console.cpp
similar/main/credits.cpp
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/kconfig.cpp
similar/main/kmatrix.cpp
similar/main/menu.cpp
similar/main/newmenu.cpp
similar/main/scores.cpp
similar/main/titles.cpp

These changes are to the dcx::window struct and related functions to allow the window struct to be subclassed (see Issue #229). In particular, this would be useful for the editor, which is currently crashing when some dialogs are opened (for example Object->AI Properties dialog).
Revising according to vLKp's feedback on #229 Allow window subclasses.

Allow window subclasses 2

---

common/arch/sdl/window.cpp
common/include/ui.h
common/include/window.h
common/ui/dialog.cpp
common/ui/file.cpp
common/ui/menu.cpp
common/ui/menubar.cpp
common/ui/message.cpp
d2x-rebirth/main/escort.cpp
d2x-rebirth/main/movie.cpp
similar/editor/centers.cpp
similar/editor/eswitch.cpp
similar/editor/info.cpp
similar/editor/med.cpp
similar/editor/medrobot.cpp
similar/editor/medwall.cpp
similar/main/automap.cpp
similar/main/console.cpp
similar/main/credits.cpp
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/kconfig.cpp
similar/main/kmatrix.cpp
similar/main/menu.cpp
similar/main/newmenu.cpp
similar/main/scores.cpp
similar/main/titles.cpp

Allow a `UI_DIALOG` to be subclassed, by adding the constructors and destructor. Doing this before attempting to make `UI_DIALOG` a subclass of window for several reasons, including because it would require its own constructor.
Also replacing the kludge of requiring all window handlers to free the window with a better solution - adding an `event_window_result::deleted`, which would be returned to `window_close` (or potentially have other uses) if the handler deleted the window.

Allow UI_DIALOG to be subclassed

---

similar/arch/ogl/ogl.cpp

The `texanis` parameter is not used in OpenGL ES, but in desktop GL. I don't know what your preferred idiom for silencing this kind of warning is. You might not want to directly merge this commit, but use something else instead. However, the classical cast-to-void works well in practice.

fix a `-Wunused-parameter` warning in the DXX_USE_OGLES code path

---

common/arch/sdl/event.cpp

Fixes freeze introduced by 9511f65a901fbbe7cc3724a99fb742ef3159d177 where `event_process` wouldn't go to the next window if it's hidden.

Fixes freeze when starting new game or editor

---

common/arch/sdl/event.cpp
common/include/ui.h
common/main/game.h
common/main/gameseq.h
common/ui/dialog.cpp
common/ui/file.cpp
common/ui/gadget.cpp
common/ui/keypad.cpp
common/ui/menubar.cpp
common/ui/ui.cpp
d1x-rebirth/editor/ehostage.cpp
d2x-rebirth/libmve/mve_main.c
similar/2d/font.cpp
similar/2d/pcx.cpp
similar/editor/kbuild.cpp
similar/editor/med.cpp
similar/editor/meddraw.cpp
similar/editor/medrobot.cpp
similar/editor/medwall.cpp
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/gameseg.cpp
similar/main/gameseq.cpp
similar/main/mission.cpp
similar/main/object.cpp
similar/main/render.cpp
similar/main/state.cpp

Fixes a bunch of bugs that existed with the editor, including:
- Crash when closing a dialog
- Crash when loading Object Properties dialog with no object selected
- File load/save not working
- Crash when loading Do Wall Dialog with no wall selected
- Stability issues after closing wall or hostage dialog
- Crash when loading editor (via delete-E) when playing a demo
- Crash when any of the required files (*.pad, *.fnt and *.mnu) are missing
- Clicking in the game view box always reporting "Click on non-texture ignored"
Note this pull request depends on #264 (as that is a much higher priority).

General fixes for the Editor

---

common/include/editor/editor.h
common/main/gameseq.h
similar/editor/kgame.cpp
similar/editor/kmine.cpp
similar/editor/med.cpp
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/gamesave.cpp
similar/main/gameseq.cpp
similar/main/state.cpp

When going to editor mode via Delete-E, save the game to _Players/gamesave.sge_ (_sge_ short for _saved game editor_). If switching back into the game via **File->Play in 320x200** without saving the level, load that saved game. The saved game can also be loaded back into the editor if the editor was subsequently launched another way (or the level was saved) with **File->Restore Game State**.
This is primarily to provide more continuity when switching between the game and the editor. The last set of changes to the editor made the player's stats reset to starting a new game when choosing **File->Play in 320x200** (as it was calling `StartNewGame`). This also maintains the game state more accurately, preserving weapon fire and various other info, as stored in the saved game file.
May also …

Used saved game loading/saving when switching between editor and a game

---

similar/main/game.cpp

Fix freeze when aborting game while demo is recording
Only return window_event_result::deleted from game_handler when Game_wind was deleted in that call of game_handler

Fix freeze when aborting game while demo is recording

---

common/main/cntrlcen.h
common/main/collide.h
common/main/endlevel.h
common/main/fwd-object.h
common/main/gameseq.h
common/main/physics.h
common/main/switch.h
similar/editor/med.cpp
similar/main/cntrlcen.cpp
similar/main/collide.cpp
similar/main/endlevel.cpp
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/gameseq.cpp
similar/main/newdemo.cpp
similar/main/object.cpp
similar/main/physics.cpp
similar/main/switch.cpp

Remove calls to `window_close(Game_wind)` as discussed in #227, replacing with returning `window_event_result::close` all the way back to `game_handler`.
There have been a number of issues picked up relating to these offending calls (e.g. #280), particularly within functions ultimately called by `game_handler`. This is an attempt to remove all such calls.
There are still three outstanding cases, but I thought I would get feedback first before going further.

Remove calls to window_close(Game_wind)

---

similar/main/newdemo.cpp

Check for `nd_record_v_no_space` in `_newdemo_write`. Fixes issue #296.

Fix crash when ran out of disk space when writing demo

---

common/main/gameseq.h
common/main/multi.h
common/main/net_udp.h
common/main/newdemo.h
common/main/state.h
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/gameseq.cpp
similar/main/multi.cpp
similar/main/net_udp.cpp
similar/main/newdemo.cpp

Remove calls to `window_close(Game_wind)` as discussed in #227, replacing with returning `window_event_result::close` all the way back to `game_handler`.
There have been a number of issues picked up relating to these offending calls (e.g. #280), particularly within functions ultimately called by `game_handler`.
This removes the three cases that were left. The somewhat contentious commit is the final one 0c5a000328058e18791aabc22d055cd27b6d2f61, as potentially a lot of code can be run between receiving a network event telling us to end the game and the game actually ending, possibly leading to unintended side effects. This is the change I was talking about in #227 @zicodxx.

Remove remaining calls to window_close(Game_wind)

---

similar/main/game.cpp
similar/main/multi.cpp
similar/main/net_udp.cpp

Fixes bug #303.
Also happened when a client to a multiplayer game dropped out due to some network error. Delay call of `multi_leave_game()` until responding to `EVENT_WINDOW_CLOSE`, so the game isn't in an unstable state between handling the network event and the game closing.

Fix debugger break at draw_weapon_info_sub when multi player dumped

---

similar/main/multi.cpp
similar/main/object.cpp

Initialise ConsoleObject->mtype.phys_info.flags in reset_player_object() instead of adding flags. The only place this was initialised properly was when reading the player object from disk.

Fix bug #306 where a client in a multi game hitting a wall fails an assert

---

common/main/robot.h
d2x-rebirth/main/escort.cpp
similar/editor/eobject.cpp
similar/main/ai.cpp
similar/main/fireball.cpp
similar/main/fuelcen.cpp

Move calls to init_ai_object into obj_create as discussed in #293 and fix a bug with the editor, where creating a level with a robot then playing it would throw an exception.

Move calls to init_ai_object into obj_create and fix robot creation bug with editor

---

common/main/player-flags.h
similar/main/state.cpp

Fix bug #309. Also keep omega cannon charge. If the player dies, keep any keys collected on the secret level - or the game will become un-winnable.

Player keeps loot if going between secret level and normal level

---

similar/main/gamecntl.cpp
similar/main/titles.cpp

Pressing ALT-B while in the briefing screens will show Dravis wearing a silly hat, for D1X-Rebirth with Mac data. Also add back the 'BALDGUY' cheat code so the next briefing featuring Dravis will show the same. Fixes bug #315.

Get 'BALDGUY' easter egg to work for D1X-Rebirth (Mac data)

---

similar/editor/eswitch.cpp

Fixes a crash when loading a level with redundant triggers and editor enabled, e.g. Passion of Death.

Don't decrement trigger in remove_trigger_num if it's trigger_none

---

similar/main/game.cpp
similar/main/gameseq.cpp

After getting game over and playing a demo or a saved game, make sure time is not stopped (i.e. allow movement), don't show the 'Game Over' banner anymore and fix a failed assert when loading a saved game.

Fix bugs after getting Game Over and playing a demo or saved game

---

common/main/ai.h
common/main/robot.h
similar/editor/medrobot.cpp
similar/main/ai.cpp
similar/main/multibot.cpp

If boss has teleported before, even before a loaded state was saved, play the boss looping sound immediately when loading the saved game (if near the boss). Resolves issue #326.
Also make the boss teleport even if it was generated by a robot maker or released by another robot. Fixes issue #328. Tacking onto this pull request because it depends on the first commit.

Fix 2 boss teleporting related issues

---

similar/main/ai.cpp

Unless there are no other segments. Fixes issue #329.

Don't teleport to original segment if boss won't fit

---

similar/main/state.cpp

Set secondary weapon flags to 0xff when saving game, so that if it's loaded with 0.58.1 or earlier the player can actually select all secondary weapons they have at least one of. Fixes issue referred to in  https://github.com/dxx-rebirth/dxx-rebirth/issues/291#issuecomment-282528356

Save secondary weapons flags for 0.58.1 compatibility

---

similar/main/ai.cpp

D1 bosses in D2 can teleport after 0.58.1.

Make sure D1 type bosses in D2 play looping sound on save game load

---

common/include/messagebox.h

msgbox_error() is defined for both Cocoa and Carbon so the define
should not be used.

Fix build break on OSX

---

common/arch/ogl/ogl_sync.cpp

This mirrors the logic from `calc_frame_time()`. When VSync is enabled, waiting for the previous frame to complete might induce long wait periods, up to the complete frame time, so we should also handle multiplayer there.
For the other sync modes, the GL calls will simply block, so we can't do anything about that (except going multithreaded, but that's a totally different can of worms). Note that even without sync, the `SwapBuffers() `call in `gr_flip()` may also block if VSync is on (and enough frames are queued up), so the issue is not the GL sync code itself.
`SYNC_GL_FENCE_SLEEP` is now probably the nicest mode for multiplayer with VSsync, as it is the only one which has the potential to continue handling multiplayer packets during the wait for VBlank time.

handle multiplayer network packets during SYNC_GL_FENCE_SLEEP wait loop

---

similar/arch/ogl/gr.cpp

Commit 449a5dffb1a376f14a6b33cb76386153dc2d3aae introduced various `glEnableClientState`/`glDisableClientState` pairs.  One of the disables got missed in `ogl_urect`.  This adds in the matching pair.
This is just an OpenGL cleanup, and should cause no visible change in game.

Add missing glDisableClientState call

---

similar/misc/physfsx.cpp

This replaces the deprecated FSRef-dependant calls to their modern CoreFoundation equivalents.

Quiet FSRef warnings

---

SConstruct
common/arch/sdl/digi_mixer_music.cpp
common/include/adlmidi_dynamic.h
common/music/adlmidi_dynamic.cpp

This is a starting point in order to add OPL3 FM into Rebirth.
This follows the discussion on #407 
[libADLMIDI](https://github.com/Wohlstand/libADLMIDI) is a synthesizer supporting General MIDI, it is able to take GM sequences and play them on multiple emulated chips, not necessarily FM sequences which were designed for single chip sound cards.
This adds a dynamic loader for the library, permitting to escape the licensing restriction of the GPL.
I have added support code for Windows and Mac, but not tested, maybe these platforms will need some help locating the libraries, like setting a DLL search path in the case of Windows.
I enumerated a number a embedded banks, for some quick tries on my side.
Some of embedded Descent banks seem not in usual GM format or not complete (commented), I …

libADLMIDI for synthesis of MIDI sequences on OPL3 FM

---

similar/arch/ogl/gr.cpp

When picking up a cloaking device in Descent 1 or 2 on DOS, the screen dims briefly. This was not present on Rebirth after conversion to OpenGL because of how the palette effect is applied; any negative values, if even given, would simply get clamped by GL, preventing them from having any effect.
Testing this can be done on any Descent level with a cloaking device, such as level 5 in Descent 1 (a cloak is present in the reactor room). On the DOS version, the screen noticeably dims when it is picked up, while this does not happen on Rebirth, giving the player fewer visual cues that they have activated a cloaking device.
This PR re-introduces the effect by modifying the OpenGL code. First, gr_palette_step_up is modified to accept negative values and pass them to GL via ogl_do_palfx, which …

Dim the screen when cloak is picked up

---

similar/main/endlevel.cpp

In the original DOS version, the mine keeps rendering even after the large explosion that "destroys" the exit hatch. For all well-lit mines (including all mines in Descent 1) that have a completely dark end of the exit tunnel, the level will simply show up as black.
In Rebirth however, the mine stops rendering once the large explosion happens. Therefore, currently, without this change, once the exit hatch is destroyed, the terrain texture will instead show through the hatch entrance, which looks fairly awkward. 
The mine stops rendering because the `Render_depth` is gradually decreased under `render_external_scene`. Disabling this would cause the mine to be rendered, but it would appear on top of the terrain regardless of whether it should for a given pixel. This could be addressed with …

Add black shape to cover exit hatch space

---

common/main/piggy.h
similar/main/mission.cpp
similar/main/piggy.cpp

This change causes game sounds to be reloaded and read from disk again every time a new mission is loaded when playing Descent 2 (D2X), allowing missions to have custom .s11/.s22 files within the HOG and therefore do sound changes. Granted, the s11/s22 files have to be named descent2.s11 and descent2.s22, but this is better than nothing before where the only way to change the sounds would be to use a dxa or replace the game files manually.
This change should have no effect on D1X.
Notes:
* This could be optimized by reloading the sounds only if we either detect a custom sound file or the last mission had one (so that sounds would reset when going back to the builtin D2 mission, for instance)
* I also added a comment to read_hamfile to specify that it is _meant_ to read the .HAM from the …

Reload sounds when loading D2 mission

---

similar/main/songs.cpp

This adds a special syntax, !Rebirth.secret, that can be used to further customize the songs played in secret levels specifically. The syntax is only enabled when dxx-r.sng is used; it is not accepted from descent.sng.
The way the syntax works is that the music file are added on a line like any other entry, but prefixed with `!Rebirth.secret `. If this is done, the music will instead be added onto a separate "secret level" playlist that is separate from the main playlist but works identically, in that having 3 secret level songs but 4 secret levels means that the fourth level will play the same music as the first one.
An example of the syntax would be:
``` 
game01.flac
game02.flac
game03.flac
!Rebirth.secret games1.flac
```

dxx-r.sng: add !Rebirth.secret

---

common/arch/sdl/event.cpp
common/arch/sdl/joy.cpp
common/include/joy.h
common/main/kconfig.h
similar/main/kconfig.cpp

Each axis can act as two buttons in both ways.
For example, a player might map slide left and slide right to J1 -A1 and J1 +A1 as button presses instead of the slide L/R axis.
This is mostly to fix XBox 360 Controller Left and Right triggers. But it can work on every axis if the player wishes to bind them.

Added axis buttons

---

SConstruct
d1x-rebirth/README.RPi
d2x-rebirth/README.RPi

The new Raspberry Pi 4B revision has a minimum requirement of Raspbian
buster, and uses the Mesa V3D driver by default; in fact, the legacy
Broadcom drivers are no longer compatible with its VideoCore VC6 chip, so
building against Mesa is mandatory for this Pi revision.
Unfortunately, the Debian buster version of the Mesa packages
have intentionally dropped the GLESv1 headers, making building of GLESv1
software impractical (even though the VC4/V3D driver can still run GLESv1
applications).
The OpenGL driver in conjunction with SDL2* runs at full
speed on Raspberry Pi 3B & 4B, so it makes sense to modify the "mesa"
build to this configuration in light of these facts.
* SDL2 is highly desirable due to the availability of the KMSDRM driver, which is
the only way to run dxx-rebirth outside of …

Update Raspberry Pi Mesa build for Buster & Pi 4B

---

SConstruct

When targeting Raspberry Pi with legacy drivers, the following error
is observed on Raspbian buster with gcc 8.3.0:
cc1plus: error: =/opt/vc/include: No such file or directory [-Werror=missing-include-dirs]
cc1plus: error: =/opt/vc/include/interface/vcos/pthreads: No such file or directory [-Werror=missing-include-dirs]
cc1plus: error: =/opt/vc/include/interface/vmcs_host/linux: No such file or directory [-Werror=missing-include-dirs]
The error can be resolved by removing the equals sign from these definitions.

SConstruct: remove equals sign from RPI -isystem definitions

---

SConstruct
common/arch/win32/rbaudio.cpp
common/include/rbaudio.h
common/main/digi.h
similar/arch/sdl/init.cpp
similar/main/config.cpp
similar/main/menu.cpp
similar/main/songs.cpp

This readds Red Book (CD Audio) support for Win32 when using SDL2. With SDL2, there are no SDL functions for handling CD playback, unlike in SDL1. Therefore we need to implement our own code, and  this case, I implemented something that works on top of MCI. This allows using CD music on SDL2, although only on Windows for now.
common/arch/win32/rbaudio.cpp is a bit messy right now, since it only contains anything if we are on SDL2, but is still compiled even on SDL1 as long as the platform is Win32. It's probably a better idea to remove those #if's and modify the SConstruct script to include it only if both SDL2 and Win32, but I don't have the expertise to work with SConstruct scripts to a sufficient degree.
There are some hacks in the code - the most major one allows track end detection …

SDL2+Win32: readd Red Book support

---

similar/arch/ogl/ogl.cpp

Fix data = NULL crash in ogl_loadtexture after piggy_bitmap_page_out_all() ran at an unfortunate time. Happens with an unreleased level by TRUEpiiiicness.
https://descentbb.net/viewtopic.php?f=22&t=24641

Add PIGGY_PAGE_IN to ogl_cache_polymodel_textures

---

similar/main/menu.cpp

newpath is a std::array and does not decay to char* automatically.
Use data() method to get char[], which does decay to char*.
This compile-time issue only affected Mac OS X.

Fix bug in select_file_handler

---

similar/main/laser.cpp

The code that provides the 0.75x multiplier to laser bolts when they're fired using the quad laser is present in D1 as in D2, however it is incorrect and results in it not being applied. As such, it is more accurate to exclude the multiplier when compiling D1.
The relevant line in D1 is `else if ((weapon_type == LASER_ID) && (Players[Objects[parent].id].flags & PLAYER_FLAGS_QUAD_LASERS))`, which looks correct, but LASER_ID refers to the blue robot laser rather than any player laser types.
Thanks to SaladBadger for the tip (and the relevant segment of D1 code).

Exclude D1 player lasers from the quad laser damage reduction

---

common/3d/clipper.cpp

| common/3d/clipper.cpp:29:14: error: 'out_of_range' is not a member of 'std'
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

clipper.cpp: Fix build with gcc10

---

similar/main/fireball.cpp

Currently, if a prison door is one-sided, the destruction of that side of the prison door will always attempt to process the destruction for a wall on the other side even if one isn't present, which causes a crash. This should fix the problem in an acceptable manner.

Prevent the destruction of one-sided prison doors from causing a crash

---

similar/arch/ogl/ogl.cpp
similar/main/polyobj.cpp

Fixes for two bugs that plagued DXX-Rebirth on Raspberry Pi systems:
- empty automap (no lines drawn)
- Medium Hulk and Heavy Hulk models were missing their heads

Raspberry Pi bugfixes

---

common/arch/cocoa/tool_bundle.py

There were a couple of errors in common/arch/cocoa/tool_bundle.py which prevented compilation on macOS.  Specifically, it was failing to properly get the app bundle suffix, and it was failing to substitute into the plist files properly.
This fixes those errors.

Fixed macOS compilation

---

similar/main/digiobj.cpp

In the original code there was a 'Hack to keep sounds from building up...'
which changed a non-forever linked sound to a non-linked sound. Therefore
the forever flag wasn't needed in the demo files. The commit
4a98e796abb099eb4c592d9520e4edbef7a15d7e removed the hack, which caused
non-forever sounds to start looping on demo playback.
This commit restores the hack as far as demo files are concerned.
Reported-by: zicodxx <https://github.com/dxx-rebirth/dxx-rebirth/issues/477>
Fixes: 4a98e796abb099eb4c592d9520e4edbef7a15d7e ("Prevent stacking weapon rotation sounds")

Workaround for missing forever flag in sound object demo recording

---

similar/main/gauges.cpp

Check if the cockpit window textures are still valid when reusing the
previous cockpit data in cockpit_decode_alpha.
This fixes a crash when leaving the graphics options menu while in
the game with cockpit visible, since that calls
ogl_smash_texture_list_internal which invalidates all textures.

Ensure cached cockpit textures are valid

---

SConstruct

Commit https://github.com/dxx-rebirth/dxx-rebirth/commit/969caa8c0cb5de8a8af29e7368ca2d21c02e34d7 (which didn't get captured in that experimental branch) broke compilation on macOS.  In macOS, the OpenGL headers and libraries are included in a framework that's bundled as part of the system SDK, so the test always fails.  However, since they're included as part of the system SDK, they should be guaranteed to always be there unless somebody's build environment is broken.

Fixed macOS compilation by bypassing GL library check

---

INSTALL.markdown

I attempted to compile this on a fresh macOS install with a fresh Homebrew install, and it looks like there were a couple of dependencies that were missed in the instructions.

Added missing Homebrew dependencies

---

similar/main/bm.cpp

Commit cb2b844 and subsequent commits changed load_exit_models to only
call bm_free_extra_objbitmaps if EMULATING_D1. The variable
extra_bitmap_num is initialized as a side effect of
bm_free_extra_objbitmaps, so it wasn't initialized anymore if
not EMULATING_D1. This broke the exit sequence with the
D2 Mac Demo data and add-on missions with custom exit sequences.
This commit adds initialization of extra_bitmap_num if not EMULATING_D1
to fix the exit handling.

always init extra_bitmap_num in load_exit_models

---

similar/main/menu.cpp

The difficulty menu is affected by the same issue as the new game menu: https://github.com/dxx-rebirth/dxx-rebirth/issues/564
The fix is also identical: point to the top level canvas in the constructor.

Fix alignment of difficulty menu text

---

INSTALL.markdown
contrib/msys2/README.md
contrib/msys2/d1x-32bit.bat
contrib/msys2/d1x-64bit.bat
contrib/msys2/d2x-32bit.bat
contrib/msys2/d2x-64bit.bat

First commit: it was always `BIN_DIR`, not `BINDIR`, as far as I can tell. Just something I noticed a while back while learning to build this project natively.
Second commit: This is the simplest way I've found to build dxx-rebirth on Windows. I welcome nitpicks if you think the layout doesn't match the rest of the document or whatever.

Instructions for building with MSYS2

---

similar/main/menu.cpp

The screen resolution menu is affected by the same issue as the new game menu: https://github.com/dxx-rebirth/dxx-rebirth/issues/564
I applied the same fix as before: point to the top level canvas in the constructor. I hope my cargo cult programming skills are up to the task :)

Fix alignment of screen resolution menu text

---

INSTALL.markdown
SConstruct

I'm having trouble figuring out how to test for the existence of a binary named `dylibbundler` on the system path, but these changes implement steps 6 and 7 from https://github.com/dxx-rebirth/dxx-rebirth/issues/561 and add a note about the additional dependency in INSTALL.markdown.

Embed dylibs in app bundles

---

INSTALL.markdown
SConstruct
common/include/args.h
common/include/ogl_init.h
common/main/game.h
common/main/kconfig.h
common/main/powerup.h
similar/arch/ogl/ogl.cpp
similar/main/collide.cpp
similar/main/game.cpp
similar/main/gamecntl.cpp
similar/main/gamemine.cpp
similar/main/gamerend.cpp
similar/main/inferno.cpp
similar/main/menu.cpp
similar/main/powerup.cpp
similar/main/render.cpp
similar/misc/args.cpp

Prepared stereo-patch for re-introducing basic stereo rendering based on Descent 1.5 StereoGraphics/SimulEyes port. 
Let me know if this patch might better be suited for separate branch for time being. 
Initially attempted to support OGL stereo quad buffering for GL_STEREO capable graphics boards + LCS glasses, which might not be getting properly supported in SDL layer. Active via '-gl_stereo' option.
Then added fallback stereo rendering mode for half-height and half-width formats. Side-by-side formats were typical for HMDs, and above/below format was amenable to LCS glasses + sync doublers. Active via '-gl_stereoview [1..3]' options.
Disabled all planar graphics elements like cockpit, status bar, and HUD elements to avoid interference with stereo rendered views. (HUD effects in Descent …

Stereo patch

---

similar/main/switch.cpp

Currently, a door locking or unlocking trigger will cause a crash if given a location where there isn't a wall. This is not inline with original behaviour, as it seemingly ignores these (or at least doesn't crash consistently). This should (hopefully; it certainly seems to in my testing) make Rebirth simply ignore such invalid triggers instead.

Fix door lock/unlock triggers causing a crash when given an invalid wall location

---

similar/arch/ogl/gr.cpp

Most Macs made in the last several years (nearly a decade now) support some form of high DPI mode.  This enables using these machines' full resolutions in SDL 2.0 builds with an SDL 2.0.1-and-above flag.  Without this, the max resolution is half of the horizontal and half of the vertical resolution of the display (which then gets integer scaled by the system in both directions).

Added high DPI flag to SDL 2.0 builds for macOS

---

SConstruct
common/arch/cocoa/messagebox.mm

The way the code is today, it builds successfully on macOS, but it throws a bunch of deprecation warnings.  One of these is easy to fix (the enum changes in `messagebox.mm`), which just requires changing a couple of enums to the currently suggested names.  The actual underlying values are the same, but at some point the old enum names may be removed.  So, I updated those.  This does, however, raise the minimum supported macOS version to 10.12 (at least for compilation; since the underlying integer is the same, I expect it would still run on older versions, though I don't have any handy to test on).  Given that that's five years old at this point, I don't see it as too much of an issue, but I do want to mention it.
The other issue is trickier to properly fix.  Apple deprecated OpenGL on …

Updated enums and added define to silence deprecation warnings

---

similar/main/kmatrix.cpp

Add periodic calls to send_endlevel_packet in kmatrix if
Control_center_destroyed is false.
Needed because after finishing the last level, kmatrix is called from a
different place where Control_center_destroyed is already false.
It looks like this issue was introduced in Rebirth 0.56 with the
split off of the ipx code (febe5d1). That commit removes the call to
multi_endlevel_poll2 from kmatrix_view, which did the same periodic
sends. (Maybe because in D1 Control_center_destroyed was always true
in kmatrix so it was not needed there.)
Reported-by: snytek <#520>
Fixes: febe5d1 ("Abstracting networking protocols")

Send periodic endlevel packets after last level

---

SConstruct

https://github.com/dxx-rebirth/dxx-rebirth/pull/543 disabled this test, as the OpenGL libraries are in a framework in macOS, and I wasn't really sure how to address that.  This corrects that, and now builds correctly on macOS.
I'm unable to test it on Linux or other platforms, but I believe the test should still pass on those.  However, it does need to be verified.

Re-add macOS OpenGL test

---

similar/misc/args.cpp

Currently, if both the "-debug" and "-verbose" options are provided (as was the case for me recently when attempting to read output that had "debug" priority and being confused about it not appearing, as the existing behaviour was not clear), if the "-verbose" option is provided later than the "-debug" option, it will result in debug output not being shown. This fix ensures that debug output will always be shown if the option is provided.
(as the condition for the -debug option will always be true as it currently stands, it's possible that comparison is superfluous, however I included it for consistency)

Small enhancement: set console output priority to highest given option rather than most recently specified

---

similar/main/titles.cpp

Undo change in e973dc0c which set the change animation direction delay
for every frame.

Fix exit briefing animation speed

---

common/include/3d.h

Commit https://github.com/dxx-rebirth/dxx-rebirth/commit/4fd412b2eabd1c412ede95ad1406b3226e2719b7 added an include line which refers to a header that's in a different location on macOS.  This adds a preprocessor condition to test for that and use the macOS location when compiling on macOS.

Fix gl.h include location for macOS

---

.gitignore
Brewfile
INSTALL.markdown

Homebrew has the notion of a "Brewfile", which is essentially a list of package repositories and packages to install with a single command.  It's typically used to install a full set of dependencies without requiring a user to type out an entire list.
So, I've created one here, and updated the documentation and ignore file to account for it.  I do have it installing both SDL 1.2 and SDL 2, as the project can be built with either, having them both installed doesn't cause issues, and they don't take up a whole lot of space.

Added Brewfile and updated macOS compilation instructions

---

.github/workflows/package-macos.yml

This one could probably benefit from input from @raptor, with the work they've done recently on the Github actions.
I did some thinking, and figured it'd make sense to move the dependency acquisition into a Brewfile (which has already been merged with the main tree here in https://github.com/dxx-rebirth/dxx-rebirth/pull/655) in order to minimize potential issues when somebody builds from source.  I was also thinking that it would make sense to use the same Brewfile for the Github action, so I updated the workflow on my branch, and it does seem to work just fine.  I generated and artifact in run https://github.com/Kreeblah/dxx-rebirth/runs/7850790479?check_suite_focus=true and can download and run the app bundles in it on my Mac just fine (both the D1X and D2X app bundles).
So, I think …

Use Brewfile for macOS Github builds

---

similar/arch/ogl/gr.cpp
similar/arch/ogl/ogl.cpp
similar/main/render.cpp

This makes it possible to run DXX-Rebirth with OpenGL ES and SDL2 on devices such as Odroid Go Advance and similar. For a better experience more changes are needed (such as proper support for gamepad api and better menu functionality), but such discussion would happen somewhere else other than this patchset.

Fix OpenGL ES build on SDL2.

---

Brewfile
INSTALL.markdown
SConstruct

This implements the Brewfile and documentation changes (information about SDL 2 and information about the `macos_add_frameworks` parameter when using Homebrew for dependency satisfaction), defaults macOS builds to SDL 2 and returns an error when attempting to build for macOS using SDL 1.2, per the conversation in https://github.com/dxx-rebirth/dxx-rebirth/issues/679.

Require SDL 2 for macOS builds

---

similar/main/ai.cpp

Gun point calculation is skipped in do_ai_frame if dist_to_player >= 200 but a bot might still fire a homing weapon if it is further away.
Add extra call to calc_gun_point in ai_do_actual_firing_stuff when a homing weapon is fired without visibility to make sure a valid gun point is used.
This is an original game bug, shown for example in this video: https://www.youtube.com/watch?v=2dP51znGh7o

Make sure gun point is calculated when firing

---

common/include/partial_range.h
common/main/d_enumerate.h
common/main/d_zip.h

Looks like there are a couple instances of `std::ranges` that need to be switched over to the ranges backport for macOS compilation to succeed.

Fix macOS compilation

---

.github/workflows/package-macos.yml

Needed since the macos-11 compiler doesn't support std::ranges.

Use macos-12 in github macOS workflow

---

common/misc/physfsrwops.cpp

SEEK_CUR and SEEK_END were not handled correctly.

Fix physfsrwops_seek for SDL2

---

similar/arch/sdl/digi_mixer.cpp

Use extended open function Mix_OpenAudioDevice to set allowed_changes to 0.
Prevents higher pitched sound on Windows.

Make sure SDL2 uses specified audio format

---

common/main/cli.cpp
similar/2d/font.cpp
similar/arch/ogl/ogl.cpp
similar/main/multi.cpp
similar/main/newmenu.cpp
similar/main/state.cpp

Xcode 14.3 was released a few days ago, which bumped Clang to 14.0.3 and libcxx to 15.x.  Some part of these changes caused compilation to generate some new warnings, with a few of those (the ones for set-but-unused variables) being promoted to errors.  This fixes those warnings, so the tree compiles cleanly on Apple Clang again.
Separately, the update also means that the ranges backports are no longer necessary for up-to-date versions of Apple Clang.  I was able to successfully compile the tree with the changes in this pull request and an additional change to set the preprocessor checks in `backports-ranges.h` to a nonexistant macro.  I haven't changed anything regarding that in this pull request, though.

Fix Apple Clang errors and warnings

---

similar/main/laser.cpp

Upon a review of D2 weapon damage, it would appear that D2 did not apply the quad laser per-bolt damage penalty to super lasers; the code was written with it clearly being intended, but as SUPER_MAX_LASER_LEVEL was inexplicably set to 5, it only checked for a laser id between 1 and 5 (LASER_ID to LASER_ID + 4), however the super lasers used ID 30 and 31, and as such did not lose damage. (see LASER.C line 644 for reference)

Fix inaccurate handling of D2 super laser damage with quad-lasers

---

SConstruct

The wrapper does not define SDL_VIDEO_OPENGL in SDL_config.h. This appears to be deliberate, although it's not entirely clear why.
/* Don't define most of the SDL backends, under the assumption checking for these against the headers won't work anyhow.
The exception is the X11 backend; you need its define to know if you can use its syswm interface. */
We could check SDL2's SDL_config.h instead, but that seems awkward to pull off.
Closes: https://github.com/dxx-rebirth/dxx-rebirth/issues/689

Skip SDL OpenGL build check when the SDL2 wrapper is detected

---

common/3d/draw.cpp
similar/main/gamefont.cpp

One issue was just a missing header. The other issue was unconditional inclusion of an OpenGL header.

Fix building without OpenGL

---

similar/main/wall.cpp

The current version of clang on macOS yields this error when compiling D2X:
```
CXX d2x build/ similar/main/wall.cpp
similar/main/wall.cpp:1429:3: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
std::remove_if(r.begin(), r.end(), std::ref(rp));
^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [build/similar/main/.d2x-rebirth.wall.o] Error 1
```
So, this explicitly discards the return value from that `std::remove_if` call there.  Applying it results in a clean build.

Fix macOS builds with current clang version

---

similar/arch/sdl/digi_mixer.cpp
similar/main/ai.cpp
similar/main/gameseq.cpp
similar/main/laser.cpp
similar/main/weapon.cpp

This attempts to address the perceived volume issues noted in #753.
As @vLKp noted, old pre- 20a0166c builds had an unintentional effect of double-scaling certain (most) sounds, but not others. This PR attempts to emulate this behavior by instead double-scaling overall Mix_Volume, instead of the Mix_Distance call on individual sounds.
It also reverts any of the individual volume intensity changes made, restoring the overall expected mix.
(particularly with -nosdlmixer)
An interesting side-effect of the old double-scaling is that it actually set the perceived sound volume - at least on Windows - closer to the perceived midi volume? I couldn't find any obvious reason for this in the Rebirth code itself, but my best guess is the system's midi volume scaling may be accounting for [logarithmic …

Restore older Rebirth perceived digi_mixer volume

---

similar/main/automap.cpp

This was the error:
```
g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_I -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/main -I/usr/include/libpng16 -I/usr/include/SDL …
```

Fix building without OpenGL using GCC 14

---

similar/main/config.cpp

It looks like https://github.com/dxx-rebirth/dxx-rebirth/commit/fca4790731cabe5ae491d0753cc4be5b9c0a465d missed getting a few macOS specific areas updated to use the new enums where tracks are referenced, which was breaking the build on macOS.  This fixes that, and allows it to build again.

Update to music enums for macOS build

---

d1x-rebirth/io.github.dxx_rebirth.dxx_rebirth.d1x-rebirth.metainfo.xml
d2x-rebirth/io.github.dxx_rebirth.dxx_rebirth.d2x-rebirth.metainfo.xml

I got the package names wrong here, as I've found out when trying to get this through Flathub's CI. The first four components should be io.github.owner.repository, and of course there are no `dxx-rebirth/d1x-rebirth`/`dxx-rebirth/d2x-rebirth` repositories. Fixed that...

Fix package names

---

common/misc/ignorecase.cpp

Currently, macOS compilation is failing with:
```
common/misc/ignorecase.cpp:62:20: error: variable 'r' set but not used [-Werror,-Wunused-but-set-variable]
62 |     if (const auto r = PHYSFS_exists(buf))
|                    ^
1 error generated.
scons: *** [build/common/misc/ignorecase.o] Error 1
scons: building terminated because of errors.
```
It looks like that variable isn't used anywhere, so this just changes that check to not save the result of `PHYSFS_exists()` and just use it in the `if` statement instead.

Fix macOS compilation by removing unused variable
